export const SECTIONS = [
  {
    id: 's1', color: '#1D9E75', badge: 'Priority 1', badgeStyle: { background: '#E1F5EE', color: '#0F6E56' },
    title: '1 · Monitoring & Observability',
    meta: '162 min video · Basic: ~1 week · Pro: ~3 days · Start: May 5',
    whyFirst: 'Prometheus + Grafana + Loki is used at most companies right now. You can set this up at your current job. Interviewers ask about it constantly.',
    labBasic: 'A running Grafana dashboard showing metrics from one service. One screenshot on GitHub. One blog post.',
    labPro: 'Add Loki log ingestion + configure one Slack alert. Blog post with architecture diagram.',
    videos: [
      { n: 250, t: 'Introduction to Monitoring', m: '15m' },
      { n: 251, t: 'Why Monitoring is Essential', m: '3m' },
      { n: 252, t: 'Monitoring & Observability Tools', m: '13m' },
      { n: 253, t: 'Setting Up Environment', m: '15m' },
      { n: 254, t: 'Loki & Web Server Setup', m: '20m' },
      { n: 255, t: 'Adding a Node to Prometheus', m: '16m' },
      { n: 256, t: 'Understanding PromQL', m: '16m' },
      { n: 257, t: 'Connecting Grafana & Prometheus', m: '7m' },
      { n: 258, t: 'Slack Notifications', m: '4m' },
      { n: 259, t: 'PromQL for Grafana Dashboards', m: '12m' },
      { n: 260, t: 'Building Grafana Panels', m: '17m' },
      { n: 261, t: 'Creating Alerts & Thresholds', m: '11m' },
      { n: 262, t: 'Loki + Alloy for Logs & Metrics', m: '13m' },
    ],
  },
  {
    id: 's2', color: '#534AB7', badge: 'Priority 2', badgeStyle: { background: '#EEEDFE', color: '#3C3489' },
    title: '2 · Docker Deep Dive',
    meta: '128 min video · Basic: ~1 week · Pro: ~3 days · Start: ~May 12 (Basic) / May 8 (Pro)',
    whyFirst: 'Docker is the foundation of GitOps and EKS (section 4). You need containers solid before the capstone.',
    labBasic: 'Build a Docker image for any app. Push to Docker Hub. Blog post: "My first containerized app."',
    labPro: 'Containerize the monitoring stack from section 1 using Docker Compose. Multi-stage Dockerfile. Blog post with Compose file explained.',
    videos: [
      { n: 302, t: 'Docker Introduction', m: '19m' },
      { n: 303, t: 'Docker Setup', m: '9m' },
      { n: 304, t: 'Commands & Concepts', m: '22m' },
      { n: 305, t: 'Docker Logs', m: '8m' },
      { n: 306, t: 'Volumes', m: '17m' },
      { n: 307, t: 'Building Images', m: '21m' },
      { n: 308, t: 'Entrypoint & CMD', m: '7m' },
      { n: 309, t: 'Docker Compose', m: '15m' },
      { n: 310, t: 'Multi-Stage Dockerfile', m: '10m' },
    ],
  },
  {
    id: 's3', color: '#D85A30', badge: 'Priority 3', badgeStyle: { background: '#FAECE7', color: '#993C1D' },
    title: '3 · AWS VPC & Core Services',
    meta: '166 min video · Basic: ~1 week · Pro: ~3 days · Start: ~May 19 (Basic) / May 10 (Pro)',
    whyFirst: 'Your AWS free tier account is active. VPC + EC2 + Lambda = the three things every cloud engineer must know.',
    labBasic: 'Build a VPC with public/private subnets + one EC2 in your AWS account. Terraform it. Blog post: "Production-like VPC on AWS free tier."',
    labPro: 'Add a bastion host + Lambda function + EC2 log shipping to CloudWatch. Blog post comparing AWS-native logs vs Loki.',
    videos: [
      { n: 263, t: 'VPC Introduction', m: '28m' },
      { n: 264, t: 'VPC Design & Components', m: '9m' },
      { n: 265, t: 'VPC Setup Details', m: '4m' },
      { n: 266, t: 'Default VPC', m: '7m' },
      { n: 267, t: 'Create VPC', m: '6m' },
      { n: 268, t: 'Subnets', m: '3m' },
      { n: 269, t: 'Internet Gateway', m: '2m' },
      { n: 270, t: 'Route Tables', m: '4m' },
      { n: 271, t: 'NAT Gateway', m: '6m' },
      { n: 272, t: 'Bastion Host', m: '9m' },
      { n: 273, t: 'Website in VPC', m: '14m' },
      { n: 274, t: 'Peering', m: '11m' },
      { n: 275, t: 'Terraform for VPC', m: '13m' },
      { n: 276, t: 'EC2 Logs', m: '31m' },
      { n: 277, t: 'AWS Lambda', m: '19m' },
    ],
  },
  {
    id: 's4', color: '#BA7517', badge: 'Priority 4', badgeStyle: { background: '#FAEEDA', color: '#854F0B' },
    title: '4 · GitOps & EKS — Capstone',
    meta: '126 min video · Basic: ~1 week · Pro: ~3 days · Start: ~May 26 (Basic) / May 13 (Pro)',
    whyFirst: 'This is the employer-visible project. GitHub Actions + Terraform + EKS auto-deploying on every commit. This one project can get you an interview.',
    labBasic: 'A working GitHub Actions pipeline that deploys to EKS. Public repo. Blog post: "GitOps pipeline from scratch."',
    labPro: 'Add the monitoring stack from section 1 to the EKS cluster. Blog series (2 posts): architecture + build walkthrough. Portfolio centrepiece.',
    videos: [
      { n: 361, t: 'GitOps Introduction', m: '7m' },
      { n: 362, t: 'Project Architecture', m: '6m' },
      { n: 363, t: 'Prepare GitHub Repo', m: '8m' },
      { n: 364, t: 'GitHub Secrets', m: '7m' },
      { n: 365, t: 'Terraform Code', m: '13m' },
      { n: 366, t: 'Staging Workflow for Terraform', m: '27m' },
      { n: 367, t: 'Main Workflow for Terraform', m: '14m' },
      { n: 368, t: 'Workflow for vProfile App', m: '17m' },
      { n: 369, t: 'Docker Build & Publish', m: '5m' },
      { n: 370, t: 'Deploy to EKS', m: '17m' },
      { n: 371, t: 'Cleanup', m: '5m' },
    ],
  },
  {
    id: 's5', color: '#888780', badge: 'Priority 5', badgeStyle: { background: '#F1EFE8', color: '#444441' },
    title: '5 · AWS CodePipeline / Beanstalk',
    meta: '73 min video · Start: ~Jun 2 (Basic) / May 17 (Pro)',
    whyFirst: 'AWS-native CI/CD. Less portable than GitHub Actions but good to know. Do after GitOps so the comparison clicks naturally.',
    labBasic: 'Deploy a simple app through CodePipeline to Beanstalk. Document the differences vs GitHub Actions.',
    labPro: 'Same as basic — this section is straightforward.',
    videos: [
      { n: 282, t: 'Introduction', m: '4m' },
      { n: 283, t: 'Beanstalk', m: '7m' },
      { n: 284, t: 'RDS & App on Beanstalk', m: '12m' },
      { n: 285, t: 'CodeCommit', m: '14m' },
      { n: 286, t: 'CodeBuild', m: '22m' },
      { n: 287, t: 'Build, Deploy & Pipeline', m: '14m' },
    ],
  },
  {
    id: 's6', color: '#888780', badge: 'Priority 6 — optional', badgeStyle: { background: '#F1EFE8', color: '#444441' },
    title: '6 · GCP vProfile Project',
    meta: '123 min video · Do only after sections 1–4 are complete',
    whyFirst: 'Montreal jobs are mostly AWS + Azure. GCP is a bonus differentiator. Skip if approaching a job search — do sections 1–4 first.',
    labBasic: 'Full vProfile app running on GCP with load balancer. Blog post: "GCP vs AWS — what I noticed."',
    labPro: 'Same as basic plus Cloud SQL performance comparison post.',
    videos: [
      { n: 288, t: 'GCP vProfile Intro', m: '11m' },
      { n: 289, t: 'Architecture Overview', m: '7m' },
      { n: 290, t: 'GCP Account Setup', m: '6m' },
      { n: 291, t: 'Commands & Source Code', m: '6m' },
      { n: 292, t: 'Project Variables', m: '7m' },
      { n: 293, t: 'VPC, Subnets & Network', m: '9m' },
      { n: 294, t: 'Firewall & VM Deployment', m: '14m' },
      { n: 295, t: 'Cloud SQL & Memorystore', m: '11m' },
      { n: 296, t: 'Cloud DNS', m: '8m' },
      { n: 297, t: 'Custom VM Image', m: '11m' },
      { n: 298, t: 'Managed Instance Group', m: '5m' },
      { n: 299, t: 'HTTP/HTTPS Load Balancer', m: '11m' },
      { n: 300, t: 'SSL & Final DNS', m: '9m' },
      { n: 301, t: 'Summary & Cleanup', m: '8m' },
    ],
  },
];

export const BASIC_WEEKS = [
  {
    week: 'Wk 3', dates: 'May 5–10',
    monTue: [['watch', '250–256 Prometheus + PromQL'], ['note', 'install Prometheus locally, run node exporter']],
    wed: [['cert', 'SC-900 Identity module']],
    thu: [['watch', '257–262 Grafana + Loki + alerts']],
    deliverable: 'Grafana dashboard screenshot on GitHub + blog post #3',
  },
  {
    week: 'Wk 4', dates: 'May 12–17',
    monTue: [['watch', '302–307 Docker basics → images']],
    wed: [['cert', 'SC-900 Security concepts module']],
    thu: [['watch', '308–310 Compose + multi-stage']],
    deliverable: 'Docker image on Docker Hub + blog post #4',
  },
  {
    week: 'Wk 5', dates: 'May 19–24',
    monTue: [['watch', '263–271 VPC core (subnets, IGW, routes)']],
    wed: [['cert', 'SC-900 Compliance module']],
    thu: [['watch', '272–277 Bastion + EC2 logs + Lambda']],
    deliverable: 'VPC + EC2 live in AWS free tier + blog post #5',
  },
  {
    week: 'Wk 6', dates: 'May 26–31',
    monTue: [['watch', '361–365 GitOps intro + Terraform']],
    wed: [['cert', 'SC-900 Practice exam questions']],
    thu: [['watch', '366–368 Staging + main workflows']],
    deliverable: 'GitHub Actions workflow running + blog post #6',
  },
  {
    week: 'Wk 7', dates: 'Jun 2–7',
    monTue: [['watch', '369–371 EKS deploy + cleanup'], ['watch', '282–287 CodePipeline']],
    wed: [['cert', 'SC-900 Full mock exam → book date']],
    thu: [['lab', 'KillerCoda K8s scenario 1']],
    deliverable: 'EKS deploy working · SC-900 booked · course 100%',
  },
];

export const PRO_WEEKS = [
  {
    week: 'Wk 3', dates: 'May 5–8',
    morning: [['watch', '250–262 Full monitoring section']],
    evening: [['deploy', 'Prometheus + Grafana + Loki running'], ['blog', 'Draft monitoring post']],
    wed: [['cert', 'SC-900 Identity + security modules']],
    deliverable: 'Dashboard + Slack alert + blog post #3 published',
  },
  {
    week: 'Wk 3–4', dates: 'May 9–12',
    morning: [['watch', '302–310 Full Docker section']],
    evening: [['deploy', 'Monitoring stack in Docker Compose'], ['blog', 'Draft Docker post']],
    wed: [['cert', 'SC-900 Compliance module']],
    deliverable: 'Docker Hub image + Compose file on GitHub + blog #4',
  },
  {
    week: 'Wk 4', dates: 'May 13–15',
    morning: [['watch', '263–277 Full AWS VPC section']],
    evening: [['deploy', 'VPC + EC2 + Lambda in real AWS'], ['blog', 'Draft VPC post']],
    wed: [['cert', 'SC-900 Practice exam']],
    deliverable: 'VPC live in AWS + Terraform code on GitHub + blog #5',
  },
  {
    week: 'Wk 4–5', dates: 'May 16–19',
    morning: [['watch', '361–371 GitOps + EKS'], ['watch', '282–287 CodePipeline']],
    evening: [['deploy', 'GitOps pipeline running on EKS'], ['blog', 'Series post 1 + 2']],
    wed: [['cert', 'SC-900 Full mock → book exam']],
    deliverable: 'EKS pipeline live · course 100% · SC-900 booked · 7–8 blog posts',
  },
];
